minimum_pre_commit_version: 3.4.0
repos:
  - repo: https://github.com/theochem/DiverseSelector
    rev:  v0.0.2
    hooks:
      - id: no-commit-to-branch
        args: [ "--branch", "main", "--branch", "staging"]
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
