# Force absolute comparison for cardboardlint
absolute: true
project:
  name: DiverseSelector
  # requirements: [[numpydoc, numpydoc], [sphinx-autoapi, sphinx-autoapi], [sphinxcontrib-bibtex, sphinxcontrib-bibtex]]
  packages:
    - dist_name: DiverseSelector
      tools:
        - write-py-version
        # - cardboardlint-static
        - build-py-inplace
        - pytest
        - upload-codecov
        # - cardboardlint-dynamic
        # - build-sphinx-doc
        # - upload-docs-gh
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        # - deploy-github
